# Generated by Django 5.1.5 on 2025-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales Associate'), ('stock_updater', 'Stock Updater'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
