# Generated by Django 5.1.5 on 2025-02-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_organizationuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Sales Associate'), ('STOCK_UPDATER', 'Stock Updater')], max_length=20),
        ),
    ]
