# Generated by Django 5.1.5 on 2025-01-24 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='med_category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='med_category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_details/')),
                ('expiry_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.category')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='MedCategory',
        ),
    ]
