# Generated by Django 5.1.5 on 2025-01-24 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_category_med_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('expiry_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.category')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='MedicineDetail',
        ),
    ]
